######################################################################
# Automatically generated by qmake (2.01a) mer. d�c. 3 22:06:51 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src
LIBS += -lcryptopp

# Input
HEADERS += src/About.h \
           src/BruteForce.h \
           src/Conversions.h \
           src/Encryptions.h \
           src/Hashes.h \
           src/History.h \
           src/Window.h
SOURCES += src/About.cpp \
           src/BruteForce.cpp \
           src/Conversions.cpp \
           src/Encryptions.cpp \
           src/Hashes.cpp \
           src/History.cpp \
           src/main.cpp \
           src/Window.cpp
RESOURCES += Qrypto.qrc
